name: CI - Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean compile
        working-directory: ./account-service

      - name: Run tests
        run: mvn -B test
        working-directory: ./account-service

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Semgrep scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/java
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Resolve dependencies (populate Maven cache)
        run: mvn -B dependency:resolve
        working-directory: ./account-service

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './account-service'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

  k8s-manifest-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Download kube-score
        run: |
          curl -Lo kube-score https://github.com/zegl/kube-score/releases/download/v1.19.0/kube-score_1.19.0_linux_amd64
          chmod +x kube-score

      - name: Scan manifest Kubernetes
        run: |
          ./kube-score score k8s/*.yaml \
            --ignore-test pod-networkpolicy \
            --ignore-test deployment-has-poddisruptionbudget \
            --ignore-test deployment-has-host-podantiaffinity \
            --ignore-test container-image-tag


  iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: tfsec scan
        run: |
          tfsec terraform/s3-and-security-group/ \
            --exclude aws-ec2-no-public-egress-sgr,aws-s3-encryption-customer-key
      
      - name: Checkov scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/s3-and-security-group
          skip_check: CKV2_AWS_62,CKV2_AWS_61,CKV2_AWS_5,CKV_AWS_144
          quiet: true

  sonarqube-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compile untuk hasil binaries
        run: mvn -B clean compile
        working-directory: ./account-service

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  notify-on-failure:
    needs:
      - build-and-test
      - secret-scan
      - sast-scan
      - dependency-scan
      - k8s-manifest-scan
      - iac-scan
      - sonarqube-scan
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify n8n on failure (webhook)
        run: |
          curl -X POST https://landlord-aviator-sizzling.ngrok-free.dev/webhook/cicd-failure-alert \
            -H "Content-Type: application/json" \
            -H "X-Webhook-Secret: ${{ secrets.N8N_WEBHOOK_SECRET }}" \
            -H "ngrok-skip-browser-warning: true" \
            -d '{"repo":"${{ github.repository }}","run_id":"${{ github.run_id }}","workflow":"${{ github.workflow }}","branch":"${{ github.ref_name }}"}'
